<?php
require_once __DIR__ . '/includes/training-lab-public-template.php';
tl_public_site_header('For Teams | Training Lab', 'Meet the team behind Training Lab.', 'about', 'Sign In', '/signin.php');
?>
<main class="tl-container tl-page-shell">
  <section class="tl-template-hero"><div class="tl-template-copy"><p class="tl-kicker">For teams</p><h1>Meet the team behind Training Lab.</h1><p>Give participants, coaches, reviewers, and managers a shared place to complete actions, verify proof, and reward progress.</p><div class="tl-actions"><a class="tl-btn tl-btn-primary" href="<?php echo tl_public_e(labs_url('/signup.php')); ?>">Join a training program</a><a class="tl-btn tl-btn-secondary" href="<?php echo tl_public_e(labs_url('/contact.php')); ?>">Contact us</a></div></div><div class="tl-template-art"><?php echo tl_public_img('about_team', 'tl-template-main-art'); ?></div></section>
  <section class="tl-team-grid"><article class="tl-member"><div class="tl-avatar"><?php echo tl_public_img('sprout'); ?></div><h3>Participants</h3><p>Complete tasks and submit proof.</p></article><article class="tl-member"><div class="tl-avatar"><?php echo tl_public_img('heart'); ?></div><h3>Coaches</h3><p>Guide progress and remove blockers.</p></article><article class="tl-member"><div class="tl-avatar"><?php echo tl_public_img('verified'); ?></div><h3>Reviewers</h3><p>Approve proof and record decisions.</p></article><article class="tl-member"><div class="tl-avatar"><?php echo tl_public_img('growth'); ?></div><h3>Managers</h3><p>Track campaigns and outcomes.</p></article></section>
  <section class="tl-section"><div class="tl-template-split"><div><?php echo tl_public_img('about_team', 'tl-template-split-art'); ?></div><div><p class="tl-kicker">Shared account model</p><h2>One user account can access Training Lab and Microgifter.</h2><p>labs.microgifter.com and microgifter.com should point users into the same account relationship, while the lab remains safe until production adapters are connected.</p><a class="tl-btn tl-btn-primary" href="<?php echo tl_public_e(labs_url('/account.php')); ?>">View account</a></div></div></section>
</main>
<?php tl_public_site_footer(); ?>
