<?php
require_once __DIR__ . '/../includes/training-lab-production-integration-closeout.php';
$root=dirname(__DIR__);$failures=[];
$check=static function(bool $condition,string $message)use(&$failures):void{if(!$condition)$failures[]=$message;};
$read=static function(string $path)use($root,$check):string{$full=$root.'/'.$path;$check(is_file($full),'Missing required file: '.$path);return is_file($full)?(string)file_get_contents($full):'';};
$service=$read('includes/training-lab-production-integration-closeout.php');$page=$read('admin/integration-closeout.php');$action=$read('admin/integration-closeout-action.php');$api=$read('api/training/integration-closeout.php');$cli=$read('bin/integration-closeout.php');$migration=$read('database/production_integration_closeout_v1.sql');$config=$read('labs/config-example.php');$acceptance=$read('includes/training-lab-product-acceptance.php');$gate=$read('run-quality-gate.sh');$workflow=$read('.github/workflows/quality-gate.yml');$docs=$read('docs/PRODUCTION-INTEGRATION-CLOSEOUT-V1.md');
foreach(['training_integration_closeout_runs','training_integration_closeout_checks','training_integration_closeout_events'] as $table)$check(str_contains($migration,$table),'Migration missing '.$table.'.');
$check(str_contains($migration,"ENUM('recorded','blocked','approved','rejected')"),'Closeout decisions require controlled states.');
$check(str_contains($migration,'report_hash CHAR(64)'),'Closeout reports require a SHA-256 fingerprint.');
$check(str_contains($migration,'UNIQUE KEY uq_training_integration_closeout_runs_report_hash'),'Identical snapshots must be idempotent.');
foreach(['account_link_active','nonce_consumed','campaign_builder_ready','sequence_receipt','pilot_graduated','participant_delivered','handoff_delivered','stage895_passed','notification_worker_disabled','reward_worker_disabled'] as $needle)$check(str_contains($service,$needle),'Missing mandatory evidence check: '.$needle);
$check(str_contains($service,'hash_equals((string)$run[\'report_hash\']'),'Approval must reject changed evidence.');
$check(str_contains($service,"run_status='approved'"),'Administrator approval must be durable.');
$check(str_contains($service,'integration_closeout_approved_immutable'),'Approved reports must be immutable.');
$check(str_contains($service,"production_integration_closeout_enabled"),'Recording must use a disabled-first gate.');
$check(str_contains($service,"production_integration_closeout_approval_enabled"),'Approval must use a separate disabled-first gate.');
$check(!preg_match('/\b(?:curl_|training_lab_send_notification_email|microgifter_training_reward_issue|tl_stage896_execute|tl_stage899_process)\b/i',$service.$action),'Closeout must not send, issue, or execute workers.');
$check(!str_contains($service,'UPDATE training_reward_handoffs'),'Closeout must not mutate reward handoffs.');
$check(!str_contains($service,'UPDATE training_notification_outbox'),'Closeout must not mutate notification delivery.');
$check(str_contains($action,"tl_security_guard_write('manage_integration_closeout'"),'Closeout decisions require protected POST writes.');
$check(str_contains($page,"'required_role'=>'admin'"),'Closeout dashboard must be administrator-only.');
$check(str_contains($api,"tl_security_require_method('GET')"),'Closeout API must be read-only GET.');
$check(str_contains($cli,"PHP_SAPI !== 'cli'"),'Closeout CLI must reject web execution.');
$check(!str_contains($cli,'--approve')&&!str_contains($cli,'--record'),'CLI must remain read-only.');
$check(str_contains($config,"'production_integration_closeout_enabled' => false"),'Recording gate must default disabled.');
$check(str_contains($config,"'production_integration_closeout_approval_enabled' => false"),'Approval gate must default disabled.');
$check(str_contains($acceptance,"'integration_closeout'=>'admin/integration-closeout.php'"),'Canonical acceptance must require closeout UI.');
$check(str_contains($acceptance,'production_integration_closeout_v1.sql'),'Canonical acceptance must require closeout migration.');
$check(str_contains($gate,'production-integration-closeout-contract-test.php'),'Local gate must run Section 20.');
$check(str_contains($workflow,'Production integration closeout contract'),'PHP matrix must run Section 20.');
$check(str_contains($docs,'Rollback')&&str_contains($docs,'Emergency stop'),'Closeout guide needs rollback and emergency stop.');
$check(str_contains($docs,'does not enable email')||str_contains($docs,'do not enable email'),'Documentation must preserve authority separation.');
$sample=tl_closeout_check('account','sample','Sample',true,'active','active','detail','evidence');
$check($sample['status']==='passed'&&strlen((string)$sample['evidence_hash'])===64,'Check normalization and evidence hashing must be deterministic.');
if($failures){fwrite(STDERR,"Production Integration Closeout contract failed:\n- ".implode("\n- ",$failures)."\n");exit(1);}echo "Production Integration Closeout contract passed.\n";
