<?php
declare(strict_types=1);
$root=dirname(__DIR__);$failures=[];
$read=static function(string $path)use($root,&$failures):string{$full=$root.'/'.$path;if(!is_file($full)){$failures[]=$path.' is missing.';return '';}return file_get_contents($full)?:'';};
$need=static function(string $body,string $needle,string $message)use(&$failures):void{if(!str_contains($body,$needle))$failures[]=$message;};
$lack=static function(string $body,string $needle,string $message)use(&$failures):void{if(str_contains($body,$needle))$failures[]=$message;};
$service=$read('includes/training-lab-reward-management.php');$queries=$read('includes/training-lab-reward-management-queries.php');$rules=$read('admin/reward-rules.php');$editor=$read('admin/reward-rule-edit.php');$analytics=$read('admin/analytics.php');$fulfillment=$read('admin/reward-bridge.php');$advanced=$read('admin/reward-operations.php');$save=$read('admin/reward-rule-save.php');$status=$read('admin/reward-rule-status.php');$nav=$read('includes/training-lab-product-shell.php');$layout=$read('includes/labs-layout.php');$css=$read('assets/css/reward-management.css');$docs=$read('docs/REWARD-RULES-ANALYTICS-OPERATIONAL-HEALTH-V1.md');$runner=$read('run-quality-gate.sh');$workflow=$read('.github/workflows/quality-gate.yml');
$need($service,'c.owner_user_id=?','Manager campaign reads must be owner scoped.');$need($service,"'platform'=>\$role === 'admin'",'Only administrators may receive platform scope.');$need($service,'LIMIT 1 FOR UPDATE','Rule writes must lock campaign and rule rows.');$need($service,'beginTransaction()','Rule writes must be transactional.');$need($service,"'draft'=>['activate'=>'active','archive'=>'archived']",'Draft lifecycle transitions must be explicit.');$need($service,"'active'=>['pause'=>'paused','archive'=>'archived']",'Active lifecycle transitions must be explicit.');$need($service,"'paused'=>['resume'=>'active','archive'=>'archived']",'Paused lifecycle transitions must be explicit.');$need($service,'reward_rule_archived','Archived rules must be immutable.');$need($service,"'wallet_write'=>false",'Rule settings must preserve the no-wallet-write boundary.');$need($service,"microgifter_authority'=>'existing_reward_bridge_only'",'Rule settings must preserve existing Microgifter authority.');$lack($service,'$_POST','Reward service must not trust raw form globals.');$lack($service,'$_GET','Reward service must not trust query globals.');
$need($queries,"re.status IN ('issued','linked')",'Delivery analytics must use actual reward delivery states.');$need($queries,'h.handoff_status','Fulfillment must use the Stage 890 handoff status column.');$need($queries,'h.failure_message','Fulfillment must use the Stage 890 failure message column.');$need($queries,"unset(\$row['id'],\$row['failure_message'])",'Fulfillment responses must remove internal database IDs and raw failure fields.');$need($queries,"substr(hash('sha256'",'Fulfillment must expose only one-way confirmation references.');$lack($queries,'payload_json','Merchant fulfillment must not read handoff payload JSON.');$lack($queries,'response_json','Merchant fulfillment must not read adapter response JSON.');$lack($queries,'idempotency_key','Merchant fulfillment must not expose idempotency keys.');$lack($queries,'external_reference','Merchant fulfillment must not expose external delivery references.');
$need($rules,'Add Reward Rule','Merchant rule library must expose rule creation.');$need($editor,'Participant preview','Editor must show a participant-facing preview.');$need($editor,'tl_security_csrf_field()','Rule editor must include CSRF protection.');$need($save,"tl_security_guard_write('evaluate_rewards'",'Save route must use the central write guard.');$need($status,"tl_security_guard_write('evaluate_rewards'",'Lifecycle route must use the central write guard.');$need($analytics,'Campaign funnel','Analytics must present a campaign funnel.');$need($fulfillment,'Track reward delivery without operating the pipeline.','Merchant fulfillment must remain observational.');$need($advanced,"'required_role'=>'admin'",'Advanced reward operations must be administrator-only.');$need($advanced,'tl_stage899_render_reward_bridge_panel','Advanced operations must preserve Stage 899 controls.');$need($advanced,'tl_stage890_render_admin_panel','Advanced operations must preserve Stage 890 controls.');$lack($fulfillment,'tl_stage890_render_admin_panel','Merchant fulfillment must not render production-operation controls.');$lack($fulfillment,'payload_json','Merchant fulfillment page must not expose payloads.');
$need($nav,"'admin-reward-rules' => ['/admin/reward-rules.php', 'Reward Rules']",'Navigation must expose reward rules.');$need($nav,"'admin-analytics' => ['/admin/analytics.php', 'Analytics']",'Navigation must expose analytics.');$need($nav,"'admin-reward-operations' => ['/admin/reward-operations.php', 'Advanced Rewards']",'Administrator navigation must expose advanced reward operations.');$need($layout,"labs_asset('css/reward-management.css')",'Shared shell must load reward management styles.');$need($css,'@media(max-width:620px)','Reward management must include a phone breakpoint.');$need($docs,'No SQL is required.','Documentation must state the SQL boundary.');$need($docs,'It does not create a second account, merchant, role, reward issuer, wallet, payment, claim, redemption, gift, or delivery authority.','Documentation must preserve authority boundaries.');$need($runner,'reward-rules-analytics-operational-health-contract-test.php','Local gate must run the Section 10 contract.');$need($workflow,'Reward rules analytics and operational health contract','CI must run the Section 10 contract.');
if($failures){fwrite(STDERR,"Reward rules, analytics, and operational health contract failed:\n- ".implode("\n- ",$failures)."\n");exit(1);}echo "Reward rules, analytics, and operational health contract passed.\n";
