<?php
require_once __DIR__ . '/../includes/labs-layout.php';
require_once __DIR__ . '/../includes/training-lab-app-service.php';
$userId = max(1, (int)($_GET['user_id'] ?? 1));
$campaignRef = isset($_GET['campaign']) ? preg_replace('/[^a-zA-Z0-9\-_]/', '', (string)$_GET['campaign']) : tl_app_default_campaign_ref();
$state = tl_stage40_launchpad_state($campaignRef, $userId);
$context = $state['participant_context'];
$nextTask = $state['next_task'];
labs_page_start(['title' => 'Daily Check-In | Training Lab', 'section' => 'app', 'active' => 'app-check-in']);
?>
<?php if (function_exists('tl_design_render_logged_in_template')) tl_design_render_logged_in_template('app-check-in'); ?>

<section class="labs-page-title labs-stage40-title"><div><span class="labs-eyebrow">Daily check-in</span><h1>Complete the next action in the training path.</h1><p class="labs-copy">Checklist tasks can auto-complete. Proof-required tasks create submitted proof for admin review. All records stay inside Training Lab tables.</p></div><div class="labs-actions"><a class="labs-btn" href="<?php echo labs_url('/app/launchpad.php?campaign=' . rawurlencode($campaignRef) . '&user_id=' . $userId); ?>">Launchpad</a><a class="labs-btn labs-btn-primary" href="<?php echo labs_url('/app/progress-map.php?campaign=' . rawurlencode($campaignRef) . '&user_id=' . $userId); ?>">Progress Map</a></div></section>
<section class="labs-flow-grid"><article class="labs-card"><span class="labs-eyebrow">Active campaign</span><h2><?php echo htmlspecialchars((string)$context['campaign']['title'], ENT_QUOTES, 'UTF-8'); ?></h2><?php if (!$context['joined']): ?><p class="labs-muted">Join this campaign before checking in.</p><form action="<?php echo labs_url('/app/action-result.php'); ?>" method="post" class="labs-stage30-form"><input type="hidden" name="confirm_training_action" value="1"><input type="hidden" name="training_action" value="cohort_invite"><input type="hidden" name="campaign_id" value="<?php echo htmlspecialchars($campaignRef, ENT_QUOTES, 'UTF-8'); ?>"><input type="hidden" name="user_id" value="<?php echo $userId; ?>"><label>Participant label<input type="text" name="participant_label" value="Demo Participant"></label><button class="labs-btn labs-btn-primary" type="submit">Join Campaign</button></form><?php elseif ($nextTask): ?><div class="labs-next-step"><span>Next task</span><strong><?php echo htmlspecialchars((string)$nextTask['title'], ENT_QUOTES, 'UTF-8'); ?></strong><p><?php echo htmlspecialchars((string)($nextTask['instructions'] ?? ''), ENT_QUOTES, 'UTF-8'); ?></p><small><?php echo !empty($nextTask['proof_required']) ? 'Proof required: review queue after submit' : 'Checklist: auto-approved Training Lab completion'; ?></small></div><?php else: ?><div class="labs-empty-state"><h3>No active task found.</h3><p>Create tasks in Campaign Builder or pick another campaign.</p></div><?php endif; ?></article><aside class="labs-card"><h2>Task path</h2><div class="labs-stage40-task-path"><?php foreach ($context['tasks'] as $task): $taskId = (string)($task['db_id'] ?? $task['id'] ?? ''); $dbTaskId = (string)($task['db_id'] ?? $task['id'] ?? ''); $proofs = $context['proofs_by_task'][$dbTaskId] ?? []; ?><div class="labs-stage40-task-node"><span><?php echo htmlspecialchars((string)($task['position'] ?? $task['position_no'] ?? ''), ENT_QUOTES, 'UTF-8'); ?></span><div><strong><?php echo htmlspecialchars((string)$task['title'], ENT_QUOTES, 'UTF-8'); ?></strong><small><?php echo $proofs ? htmlspecialchars((string)($proofs[0]['status'] ?? 'recorded'), ENT_QUOTES, 'UTF-8') : (!empty($task['proof_required']) ? 'proof required' : 'checklist'); ?></small></div></div><?php endforeach; if (!$context['tasks']): ?><p class="labs-muted">No task path available.</p><?php endif; ?></div></aside></section>
<?php if ($context['joined'] && $nextTask): ?><section class="labs-card"><div class="labs-card-headline"><div><span class="labs-eyebrow">Check in</span><h2><?php echo htmlspecialchars((string)$nextTask['title'], ENT_QUOTES, 'UTF-8'); ?></h2></div><span class="labs-pill"><?php echo !empty($nextTask['proof_required']) ? 'Proof review required' : 'Auto-complete checklist'; ?></span></div><form action="<?php echo labs_url('/app/action-result.php'); ?>" method="post" class="labs-stage30-form labs-stage40-form"><input type="hidden" name="confirm_training_action" value="1"><input type="hidden" name="training_action" value="quick_checkin"><input type="hidden" name="campaign_id" value="<?php echo htmlspecialchars($campaignRef, ENT_QUOTES, 'UTF-8'); ?>"><input type="hidden" name="task_id" value="<?php echo htmlspecialchars((string)$nextTask['id'], ENT_QUOTES, 'UTF-8'); ?>"><input type="hidden" name="user_id" value="<?php echo $userId; ?>"><label>Participant label<input type="text" name="participant_label" value="<?php echo htmlspecialchars((string)($context['participant']['participant_label'] ?? 'Demo Participant'), ENT_QUOTES, 'UTF-8'); ?>"></label><label>Reflection / proof text<textarea name="proof_text" rows="5" placeholder="What did you complete? What should the reviewer know?"></textarea></label><label>Optional external proof URL<input type="url" name="external_url" placeholder="https://example.com/proof-note"></label><button class="labs-btn labs-btn-primary" type="submit">Save Check-In</button></form></section><?php endif; ?>
<section class="labs-safe-note">Check-in may write proof, review, receipt, streak, reward-event, and event rows only inside Training Lab tables. It does not process real media uploads.</section>
<?php labs_page_end(['section' => 'app']); ?>
