<?php
require_once __DIR__ . '/../includes/labs-layout.php';
require_once __DIR__ . '/../includes/training-lab-onboarding.php';
$page=['title'=>'Getting Started | Training Lab','section'=>'app','active'=>'app-getting-started','required_role'=>'participant'];
$user=tl_product_require_page_access($page);$state=tl_onboarding_participant($user ?? []);labs_page_start($page);
?>
<section class="labs-product-hero"><article class="labs-product-hero-main"><span class="labs-product-kicker">Getting started</span><h1>Build your first verified training result.</h1><p>Follow one connected path from account and campaign enrollment to proof, completion, and reward progress.</p></article><aside class="labs-product-next"><div><span>Next step</span><h2><?php echo labs_e((string)$state['next']['label']); ?></h2><p><?php echo labs_e((string)$state['next']['detail']); ?></p></div><a class="labs-btn labs-btn-primary" href="<?php echo htmlspecialchars(labs_url((string)$state['next']['href']),ENT_QUOTES,'UTF-8'); ?>">Continue Setup</a></aside></section>
<section class="labs-product-card labs-onboarding-progress"><div><span class="labs-product-kicker">Your setup</span><h2><?php echo (int)$state['complete_count']; ?> of <?php echo (int)$state['total_count']; ?> steps complete</h2></div><div class="labs-product-progress" aria-label="<?php echo (int)$state['percent']; ?> percent complete"><span style="width:<?php echo (int)$state['percent']; ?>%"></span></div></section>
<section class="labs-onboarding-steps" aria-label="Participant onboarding checklist"><?php foreach($state['steps'] as $index=>$step): ?><article class="labs-onboarding-step<?php echo $step['complete']?' is-complete':''; ?>"><span class="labs-onboarding-index" aria-hidden="true"><?php echo $step['complete']?'✓':$index+1; ?></span><div><span class="labs-product-status is-<?php echo $step['complete']?'success':'info'; ?>"><?php echo $step['complete']?'Complete':'Next'; ?></span><h2><?php echo labs_e((string)$step['label']); ?></h2><p><?php echo labs_e((string)$step['detail']); ?></p></div><a class="labs-btn" href="<?php echo htmlspecialchars(labs_url((string)$step['href']),ENT_QUOTES,'UTF-8'); ?>"><?php echo $step['complete']?'Review':'Start'; ?></a></article><?php endforeach; ?></section>
<section class="labs-safe-note">Training Lab uses your trusted signed-in identity. This guide never asks you to select or type a participant user ID.</section>
<?php labs_page_end(['section'=>'app']); ?>
