<?php
require_once __DIR__ . '/../includes/labs-layout.php';
require_once __DIR__ . '/../includes/training-lab-app-service.php';
$userId = max(1, (int)($_GET['user_id'] ?? 1));
$campaignRef = isset($_GET['campaign']) ? preg_replace('/[^a-zA-Z0-9\-_]/', '', (string)$_GET['campaign']) : tl_app_default_campaign_ref();
$state = tl_stage40_launchpad_state($campaignRef, $userId);
$context = $state['participant_context'];
$nextTask = $state['next_task'];
labs_page_start(['title' => 'Participant Launchpad | Training Lab', 'section' => 'app', 'active' => 'app-launchpad']);
?>
<?php if (function_exists('tl_design_render_logged_in_template')) tl_design_render_logged_in_template('app-launchpad'); ?>

<?php if (function_exists('tl_stage720_render_challenge_template_selection')) tl_stage720_render_challenge_template_selection(); ?>
<?php if (function_exists('tl_stage520_render_campaign_builder')) tl_stage520_render_campaign_builder($campaignRef ?? ''); ?>
<?php if (function_exists('tl_stage560_render_campaign_publish_planner')) tl_stage560_render_campaign_publish_planner($campaignRef ?? ''); ?>


<section class="labs-page-title labs-stage40-title"><div><span class="labs-eyebrow">Participant launchpad</span><h1>Start, continue, and finish the Training Lab flow.</h1><p class="labs-copy">This is the participant-facing entry point for the standalone Training Lab app. It joins a campaign, sends the user to the next check-in, and shows progress without touching production Microgifter systems.</p></div><div class="labs-actions"><a class="labs-btn labs-btn-primary" href="<?php echo labs_url('/app/check-in.php?campaign=' . rawurlencode($campaignRef) . '&user_id=' . $userId); ?>">Continue Check-In</a><a class="labs-btn" href="<?php echo labs_url('/app/progress-map.php?campaign=' . rawurlencode($campaignRef) . '&user_id=' . $userId); ?>">Progress Map</a><a class="labs-btn" href="<?php echo labs_url('/app/flow-board.php'); ?>">Flow Board</a></div></section>
<section class="labs-kpis labs-stage40-kpis"><div class="labs-kpi"><span class="labs-muted">Mode</span><strong><?php echo htmlspecialchars($state['summary']['mode'], ENT_QUOTES, 'UTF-8'); ?></strong><small><?php echo $state['summary']['connected'] ? 'database' : 'demo fallback'; ?></small></div><div class="labs-kpi"><span class="labs-muted">Joined</span><strong><?php echo $context['joined'] ? 'Yes' : 'No'; ?></strong><small>User #<?php echo $userId; ?></small></div><div class="labs-kpi"><span class="labs-muted">Receipts</span><strong><?php echo count($context['receipts']); ?></strong><small>training-only</small></div><div class="labs-kpi"><span class="labs-muted">Rewards</span><strong><?php echo count($context['rewards']); ?></strong><small>simulated</small></div></section>
<section class="labs-flow-grid labs-stage40-grid">
  <article class="labs-card labs-stage40-hero-card"><span class="labs-eyebrow">Selected campaign</span><h2><?php echo htmlspecialchars((string)$context['campaign']['title'], ENT_QUOTES, 'UTF-8'); ?></h2><p class="labs-muted"><?php echo htmlspecialchars((string)($context['campaign']['description'] ?? $context['campaign']['summary'] ?? ''), ENT_QUOTES, 'UTF-8'); ?></p><?php if ($nextTask): ?><div class="labs-next-step"><span>Next task</span><strong><?php echo htmlspecialchars((string)$nextTask['title'], ENT_QUOTES, 'UTF-8'); ?></strong><p><?php echo htmlspecialchars((string)($nextTask['instructions'] ?? ''), ENT_QUOTES, 'UTF-8'); ?></p></div><?php else: ?><div class="labs-next-step"><span>Next task</span><strong>Join or create a campaign to begin.</strong></div><?php endif; ?></article>
  <aside class="labs-card"><h2>Campaign switcher</h2><div class="labs-panel-list"><?php foreach ($state['campaigns'] as $campaign): ?><a class="labs-panel-item labs-panel-link" href="<?php echo labs_url('/app/launchpad.php?campaign=' . rawurlencode((string)$campaign['ref']) . '&user_id=' . $userId); ?>"><span class="labs-mini-icon">C</span><div><strong><?php echo htmlspecialchars((string)$campaign['title'], ENT_QUOTES, 'UTF-8'); ?></strong><p><?php echo htmlspecialchars((string)$campaign['status'], ENT_QUOTES, 'UTF-8'); ?></p></div></a><?php endforeach; if (!$state['campaigns']): ?><p class="labs-muted">No campaigns yet. Seed demo campaigns from the Workspace.</p><?php endif; ?></div></aside>
</section>
<section class="labs-card"><div class="labs-card-headline"><div><span class="labs-eyebrow">Join / load participant</span><h2>Participant session</h2></div><span class="labs-pill">writes only training_participants + training_streaks</span></div><form action="<?php echo labs_url('/app/action-result.php'); ?>" method="post" class="labs-stage30-form labs-stage40-form"><input type="hidden" name="confirm_training_action" value="1"><input type="hidden" name="training_action" value="cohort_invite"><input type="hidden" name="campaign_id" value="<?php echo htmlspecialchars($campaignRef, ENT_QUOTES, 'UTF-8'); ?>"><label>User ID<input type="number" name="user_id" value="<?php echo $userId; ?>" min="1"></label><label>Participant label<input type="text" name="participant_label" value="<?php echo htmlspecialchars((string)($context['participant']['participant_label'] ?? 'Demo Participant'), ENT_QUOTES, 'UTF-8'); ?>"></label><button class="labs-btn labs-btn-primary" type="submit">Join / Load Participant</button></form></section>
<section class="labs-card"><h2>Current participant snapshot</h2><?php if ($context['joined']): ?><div class="labs-stage40-progress-strip"><div><span>Status</span><strong><?php echo htmlspecialchars((string)$context['participant']['status'], ENT_QUOTES, 'UTF-8'); ?></strong></div><div><span>Proofs</span><strong><?php echo count($context['proofs']); ?></strong></div><div><span>Completed</span><strong><?php echo (int)($context['streak']['completed_action_count'] ?? 0); ?></strong></div><div><span>Current streak</span><strong><?php echo (int)($context['streak']['current_streak_days'] ?? 0); ?></strong></div></div><?php else: ?><div class="labs-empty-state"><h3>This user has not joined the selected campaign yet.</h3><p>Use the participant session form above to create or load a Training Lab participant.</p></div><?php endif; ?></section>
<section class="labs-safe-note">Launchpad actions stay inside Training Lab participant/streak records. No auth gate, payment, wallet, reward issuing, upload processing, claim, or redeem logic is added.</section>
<?php labs_page_end(['section' => 'app']); ?>
