<?php
require_once __DIR__ . '/../includes/labs-layout.php';
require_once __DIR__ . '/../includes/training-lab-app-service.php';
$userId = max(1, (int)($_GET['user_id'] ?? 1));
$campaignRef = isset($_GET['campaign']) ? preg_replace('/[^a-zA-Z0-9\-_]/', '', (string)$_GET['campaign']) : tl_app_default_campaign_ref();
$state = tl_stage50_message_board_state($campaignRef, $userId);
labs_page_start(['title' => 'Message Board | Training Lab', 'section' => 'app', 'active' => 'app-message-board']);
?>
<?php if (function_exists('tl_design_render_logged_in_template')) tl_design_render_logged_in_template('app-message-board'); ?>

<?php if (function_exists('tl_stage720_render_participant_learning_experience')) tl_stage720_render_participant_learning_experience((string)($_GET['campaign'] ?? ''), max(0, (int)($_GET['user_id'] ?? 0))); ?>

<?php if (function_exists('tl_stage680_render_participant_communication')) tl_stage680_render_participant_communication((string)($_GET['campaign'] ?? ''), max(0, (int)($_GET['user_id'] ?? 0))); ?>

<section class="labs-page-title labs-stage50-title"><div><span class="labs-eyebrow">Message board</span><h1>Post Training Lab-only messages for participants and demos.</h1><p class="labs-copy">Messages are internal Training Lab event records only. They are not email, SMS, push notifications, or production app messages.</p></div><div class="labs-actions"><a class="labs-btn" href="<?php echo labs_url('/app/resource-hub.php?campaign=' . rawurlencode($campaignRef) . '&user_id=' . $userId); ?>">Resource Hub</a><a class="labs-btn labs-btn-primary" href="<?php echo labs_url('/admin/reporting-center.php'); ?>">Reporting Center</a></div></section>
<section class="labs-flow-grid"><article class="labs-card"><h2>Post message</h2><form action="<?php echo labs_url('/app/action-result.php'); ?>" method="post" class="labs-stage30-form labs-stage45-form"><input type="hidden" name="confirm_training_action" value="1"><input type="hidden" name="training_action" value="send_training_message"><input type="hidden" name="campaign" value="<?php echo labs_e($campaignRef); ?>"><label>Actor user ID<input type="number" name="actor_user_id" value="<?php echo $userId; ?>" min="1"></label><label>Recipient user ID, optional<input type="number" name="recipient_user_id" value="" min="1" placeholder="Leave blank for general board"></label><label>Topic<input type="text" name="message_topic" value="Next training step"></label><label>Message<textarea name="message_body" rows="5">Please open your next task and submit a short reflection when complete.</textarea></label><button class="labs-btn labs-btn-primary" type="submit">Post Training Message</button></form></article><aside class="labs-card"><h2>Participant targets</h2><div class="labs-stage50-table"><?php foreach (array_slice($state['participants'],0,10) as $p): ?><div><strong><?php echo labs_e((string)($p['participant_label'] ?? 'Participant')); ?></strong><span>User #<?php echo (int)($p['user_id'] ?? 0); ?></span><small><?php echo labs_e((string)($p['status'] ?? 'active')); ?></small></div><?php endforeach; if (!$state['participants']): ?><p class="labs-muted">No participants yet.</p><?php endif; ?></div></aside></section>
<section class="labs-card"><h2>Recent board messages</h2><div class="labs-stage50-message-list"><?php foreach ($state['messages'] as $event): $meta=json_decode((string)($event['metadata_json'] ?? '{}'), true) ?: []; ?><div><span><?php echo labs_e((string)($meta['message_topic'] ?? 'Message')); ?></span><p><?php echo labs_e((string)($meta['message_body'] ?? '')); ?></p><small><?php echo labs_e((string)$event['created_at']); ?> · <?php echo labs_e((string)($meta['delivery'] ?? 'training-only')); ?></small></div><?php endforeach; if (!$state['messages']): ?><p class="labs-muted">No Training Lab messages yet.</p><?php endif; ?></div></section>
<section class="labs-safe-note">The Message Board writes only training_events. It does not contact real users.</section>
<?php labs_page_end(['section' => 'app']); ?>
