<?php
require_once __DIR__ . '/../includes/labs-layout.php';
require_once __DIR__ . '/../includes/training-lab-app-service.php';
$userId = max(1, (int)($_GET['user_id'] ?? 1));
$campaignRef = isset($_GET['campaign']) ? preg_replace('/[^a-zA-Z0-9\-_]/', '', (string)$_GET['campaign']) : tl_app_default_campaign_ref();
$state = tl_stage40_launchpad_state($campaignRef, $userId);
$context = $state['participant_context'];
$completed = (int)($context['streak']['completed_action_count'] ?? 0);
$target = (int)($context['campaign']['total_actions'] ?? $context['campaign']['target_action_count'] ?? count($context['tasks']) ?: 1);
$percent = $target > 0 ? min(100, (int)round(($completed / $target) * 100)) : 0;
labs_page_start(['title' => 'Progress Map | Training Lab', 'section' => 'app', 'active' => 'app-progress-map']);
?>
<?php if (function_exists('tl_design_render_logged_in_template')) tl_design_render_logged_in_template('app-progress-map'); ?>
<?php if (function_exists('tl_stage840_render_award_history')) tl_stage840_render_award_history(max(0, (int)($_GET['user_id'] ?? 0))); ?>

<?php if (function_exists('tl_stage680_render_mission_followup_logic')) tl_stage680_render_mission_followup_logic((string)($_GET['campaign'] ?? ''), max(0, (int)($_GET['user_id'] ?? 0))); ?>
<?php if (function_exists('tl_stage640_render_participant_data_quality')) tl_stage640_render_participant_data_quality((string)($_GET['campaign'] ?? ''), max(0, (int)($_GET['user_id'] ?? 0))); ?>

<?php if (function_exists('tl_stage520_render_participant_mission')) tl_stage520_render_participant_mission((string)($_GET['campaign'] ?? ''), max(0, (int)($_GET['user_id'] ?? 0))); ?>
<?php if (function_exists('tl_stage560_render_mission_runbook')) tl_stage560_render_mission_runbook((string)($_GET['campaign'] ?? ''), max(0, (int)($_GET['user_id'] ?? 0))); ?>

<?php if (function_exists('tl_stage600_render_participant_timeline')) tl_stage600_render_participant_timeline((string)($_GET['campaign'] ?? ''), (int)($_GET['user_id'] ?? 0)); ?>


<section class="labs-page-title labs-stage40-title"><div><span class="labs-eyebrow">Progress map</span><h1>Track participant progress, receipts, and simulated rewards.</h1><p class="labs-copy">This page turns the Training Lab flow into a usable participant progress map with completion proof and certificate readiness.</p></div><div class="labs-actions"><a class="labs-btn" href="<?php echo labs_url('/app/check-in.php?campaign=' . rawurlencode($campaignRef) . '&user_id=' . $userId); ?>">Check In</a><a class="labs-btn labs-btn-primary" href="<?php echo labs_url('/admin/cohort-manager.php'); ?>">Cohort Manager</a></div></section>
<section class="labs-card labs-stage40-progress-card"><div class="labs-card-headline"><div><span class="labs-eyebrow">Progress</span><h2><?php echo htmlspecialchars((string)$context['campaign']['title'], ENT_QUOTES, 'UTF-8'); ?></h2></div><span class="labs-pill"><?php echo $percent; ?>%</span></div><div class="labs-progress-meter"><span style="width:<?php echo $percent; ?>%"></span></div><div class="labs-stage40-progress-strip"><div><span>Completed</span><strong><?php echo $completed; ?>/<?php echo $target; ?></strong></div><div><span>Proofs</span><strong><?php echo count($context['proofs']); ?></strong></div><div><span>Receipts</span><strong><?php echo count($context['receipts']); ?></strong></div><div><span>Rewards</span><strong><?php echo count($context['rewards']); ?></strong></div></div></section>
<section class="labs-flow-grid"><article class="labs-card"><h2>Task progress</h2><div class="labs-stage40-task-path"><?php foreach ($context['tasks'] as $task): $dbTaskId = (string)($task['db_id'] ?? $task['id'] ?? ''); $proofs = $context['proofs_by_task'][$dbTaskId] ?? []; $status = $proofs ? (string)($proofs[0]['status'] ?? 'recorded') : 'not started'; ?><div class="labs-stage40-task-node"><span><?php echo $status === 'approved' ? '✓' : '•'; ?></span><div><strong><?php echo htmlspecialchars((string)$task['title'], ENT_QUOTES, 'UTF-8'); ?></strong><small><?php echo htmlspecialchars($status, ENT_QUOTES, 'UTF-8'); ?></small></div></div><?php endforeach; if (!$context['tasks']): ?><p class="labs-muted">No task rows available.</p><?php endif; ?></div></article><article class="labs-card"><h2>Receipts and rewards</h2><div class="labs-panel-list"><?php foreach ($context['receipts'] as $receipt): ?><div class="labs-panel-item"><span class="labs-mini-icon">A</span><div><strong><?php echo htmlspecialchars((string)$receipt['receipt_type'], ENT_QUOTES, 'UTF-8'); ?></strong><p><?php echo htmlspecialchars((string)$receipt['public_id'], ENT_QUOTES, 'UTF-8'); ?></p></div></div><?php endforeach; foreach ($context['rewards'] as $reward): ?><div class="labs-panel-item"><span class="labs-mini-icon">R</span><div><strong><?php echo htmlspecialchars((string)($reward['reward_label'] ?: 'Simulated reward'), ENT_QUOTES, 'UTF-8'); ?></strong><p><?php echo htmlspecialchars((string)$reward['status'], ENT_QUOTES, 'UTF-8'); ?> · no wallet write</p></div></div><?php endforeach; if (!$context['receipts'] && !$context['rewards']): ?><p class="labs-muted">No receipts or reward events yet.</p><?php endif; ?></div></article></section>
<?php if ($context['joined']): ?><section class="labs-card"><div class="labs-card-headline"><div><span class="labs-eyebrow">Certificate readiness</span><h2>Finalize completion when the training path is ready.</h2></div><span class="labs-pill">preview only</span></div><form action="<?php echo labs_url('/admin/action-result.php'); ?>" method="post" class="labs-stage30-form"><input type="hidden" name="confirm_training_action" value="1"><input type="hidden" name="training_action" value="finalize_participant"><input type="hidden" name="participant_id" value="<?php echo htmlspecialchars((string)$context['participant']['public_id'], ENT_QUOTES, 'UTF-8'); ?>"><input type="hidden" name="actor_user_id" value="1"><button class="labs-btn labs-btn-primary" type="submit">Create Completion Certificate Receipt</button></form></section><?php endif; ?>
<section class="labs-safe-note">Certificates are Training Lab action receipts. They are not Microgifter claims, rewards, payments, wallet credits, or redemption records.</section>
<?php labs_page_end(['section' => 'app']); ?>
