<?php
require_once __DIR__ . '/../includes/labs-layout.php';
require_once __DIR__ . '/../includes/training-lab-app-service.php';
$userId = max(1, (int)($_GET['user_id'] ?? 1));
$campaignRef = isset($_GET['campaign']) ? preg_replace('/[^a-zA-Z0-9\-_]/', '', (string)$_GET['campaign']) : tl_app_default_campaign_ref();
$state = tl_stage45_reflection_state($campaignRef, $userId);
labs_page_start(['title' => 'Reflection Journal | Training Lab', 'section' => 'app', 'active' => 'app-reflection-journal']);
?>
<?php if (function_exists('tl_design_render_logged_in_template')) tl_design_render_logged_in_template('app-reflection-journal'); ?>

<?php if (function_exists('tl_stage720_render_participant_learning_experience')) tl_stage720_render_participant_learning_experience((string)($_GET['campaign'] ?? ''), max(0, (int)($_GET['user_id'] ?? 0))); ?>

<section class="labs-page-title labs-stage45-title"><div><span class="labs-eyebrow">Reflection journal</span><h1>Turn learning notes into reviewable Training Lab proof.</h1><p class="labs-copy">Participants can submit text-only reflections into the proof queue. This is a Training Lab record, not a real file upload.</p></div><div class="labs-actions"><a class="labs-btn" href="<?php echo labs_url('/app/participant-portal.php?campaign=' . rawurlencode($campaignRef) . '&user_id=' . $userId); ?>">Participant Portal</a><a class="labs-btn labs-btn-primary" href="<?php echo labs_url('/admin/review-workbench.php'); ?>">Review Workbench</a></div></section>
<section class="labs-flow-grid"><article class="labs-card"><h2>Submit journal proof</h2><form action="<?php echo labs_url('/app/action-result.php'); ?>" method="post" class="labs-stage30-form labs-stage45-form"><input type="hidden" name="confirm_training_action" value="1"><input type="hidden" name="training_action" value="submit_reflection_journal"><label>Campaign<select name="campaign_id"><?php foreach ($state['campaigns'] as $campaign): ?><option value="<?php echo htmlspecialchars((string)$campaign['ref'], ENT_QUOTES, 'UTF-8'); ?>" <?php echo (string)$campaign['ref'] === $campaignRef ? 'selected' : ''; ?>><?php echo htmlspecialchars((string)$campaign['title'], ENT_QUOTES, 'UTF-8'); ?></option><?php endforeach; ?></select></label><label>Task<select name="task_id"><?php foreach ($state['tasks'] as $task): ?><option value="<?php echo htmlspecialchars((string)$task['id'], ENT_QUOTES, 'UTF-8'); ?>"><?php echo htmlspecialchars((string)$task['title'], ENT_QUOTES, 'UTF-8'); ?></option><?php endforeach; ?></select></label><label>User ID<input type="number" name="user_id" value="<?php echo $userId; ?>" min="1"></label><label>Participant label<input type="text" name="participant_label" value="<?php echo htmlspecialchars((string)($state['context']['participant']['participant_label'] ?? 'Reflection Participant'), ENT_QUOTES, 'UTF-8'); ?>"></label><label>Prompt<input type="text" name="journal_prompt" value="What did you learn from this action?"></label><label>Reflection<textarea name="reflection_text" rows="8">I completed the training action and can explain what changed, what I learned, and what should happen next.</textarea></label><button class="labs-btn labs-btn-primary" type="submit">Submit Reflection Proof</button></form></article><aside class="labs-card"><h2>Journal boundary</h2><p class="labs-muted">This creates a text proof record in training_proof_submissions and logs a Training Lab event. It does not process uploads or external media.</p><div class="labs-stage30-count-list"><div><span>Available tasks</span><strong><?php echo count($state['tasks']); ?></strong></div><div><span>Proofs</span><strong><?php echo count($state['context']['proofs'] ?? []); ?></strong></div><div><span>Reviews</span><strong><?php echo count($state['context']['reviews'] ?? []); ?></strong></div></div></aside></section>
<section class="labs-safe-note">Reflection Journal creates Training Lab text proof only. No media upload processing, wallet, reward issuing, payments, claims, or redeems.</section>
<?php labs_page_end(['section' => 'app']); ?>
