-- Training Lab Limited Live Email Pilot + Graduation v1
-- Import after pilot_operations_communications_v1.sql and notification_provider_webhooks_v1.sql.
-- Additive Training Lab operations schema only. No Microgifter account, wallet,
-- payment, gift, claim, redemption, or reward-delivery table is altered.

CREATE TABLE IF NOT EXISTS training_notification_pilot_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    campaign_id BIGINT UNSIGNED NOT NULL,
    owner_user_id BIGINT UNSIGNED NOT NULL,
    run_status ENUM('draft','canary_sent','canary_confirmed','approved','running','paused','graduated','rejected','cancelled') NOT NULL DEFAULT 'draft',
    cohort_limit INT UNSIGNED NOT NULL DEFAULT 5,
    batch_limit INT UNSIGNED NOT NULL DEFAULT 1,
    daily_limit INT UNSIGNED NOT NULL DEFAULT 10,
    minimum_delivery_rate_percent INT UNSIGNED NOT NULL DEFAULT 100,
    webhook_timeout_seconds INT UNSIGNED NOT NULL DEFAULT 900,
    delay_timeout_seconds INT UNSIGNED NOT NULL DEFAULT 1800,
    maximum_bounces INT UNSIGNED NOT NULL DEFAULT 0,
    maximum_complaints INT UNSIGNED NOT NULL DEFAULT 0,
    maximum_provider_failures INT UNSIGNED NOT NULL DEFAULT 0,
    maximum_orphaned_events INT UNSIGNED NOT NULL DEFAULT 0,
    canary_outbox_id BIGINT UNSIGNED DEFAULT NULL,
    canary_status ENUM('not_sent','accepted','sent','delivered','delayed','failed','bounced','complained','suppressed') NOT NULL DEFAULT 'not_sent',
    canary_provider_message_hash CHAR(64) DEFAULT NULL,
    canary_sent_at DATETIME DEFAULT NULL,
    canary_confirmed_at DATETIME DEFAULT NULL,
    approved_by_user_id BIGINT UNSIGNED DEFAULT NULL,
    approved_at DATETIME DEFAULT NULL,
    started_by_user_id BIGINT UNSIGNED DEFAULT NULL,
    started_at DATETIME DEFAULT NULL,
    paused_by_user_id BIGINT UNSIGNED DEFAULT NULL,
    paused_at DATETIME DEFAULT NULL,
    paused_reason VARCHAR(255) DEFAULT NULL,
    graduated_by_user_id BIGINT UNSIGNED DEFAULT NULL,
    graduated_at DATETIME DEFAULT NULL,
    rejected_by_user_id BIGINT UNSIGNED DEFAULT NULL,
    rejected_at DATETIME DEFAULT NULL,
    decision_notes VARCHAR(500) DEFAULT NULL,
    created_by_user_id BIGINT UNSIGNED NOT NULL,
    updated_by_user_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_training_notification_pilot_runs_public (public_id),
    KEY idx_training_notification_pilot_runs_campaign (campaign_id, created_at),
    KEY idx_training_notification_pilot_runs_status (run_status, updated_at),
    KEY idx_training_notification_pilot_runs_canary (canary_outbox_id, canary_provider_message_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS training_notification_pilot_members (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    pilot_run_id BIGINT UNSIGNED NOT NULL,
    participant_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    account_link_id BIGINT UNSIGNED NOT NULL,
    recipient_hash CHAR(64) NOT NULL,
    member_status ENUM('eligible','active','completed','suppressed','removed') NOT NULL DEFAULT 'eligible',
    selected_by_user_id BIGINT UNSIGNED NOT NULL,
    activated_at DATETIME DEFAULT NULL,
    completed_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_training_notification_pilot_members_public (public_id),
    UNIQUE KEY uq_training_notification_pilot_members_run_participant (pilot_run_id, participant_id),
    KEY idx_training_notification_pilot_members_run_status (pilot_run_id, member_status),
    KEY idx_training_notification_pilot_members_user (user_id, pilot_run_id),
    KEY idx_training_notification_pilot_members_account (account_link_id, member_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS training_notification_pilot_checks (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    check_group_id CHAR(36) NOT NULL,
    pilot_run_id BIGINT UNSIGNED NOT NULL,
    check_key VARCHAR(96) NOT NULL,
    check_label VARCHAR(191) NOT NULL,
    check_status ENUM('passed','failed','pending') NOT NULL,
    observed_value VARCHAR(191) DEFAULT NULL,
    required_value VARCHAR(191) DEFAULT NULL,
    detail VARCHAR(500) DEFAULT NULL,
    evaluated_by_user_id BIGINT UNSIGNED DEFAULT NULL,
    evaluated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_training_notification_pilot_checks_public (public_id),
    UNIQUE KEY uq_training_notification_pilot_checks_group_key (check_group_id, check_key),
    KEY idx_training_notification_pilot_checks_run (pilot_run_id, evaluated_at),
    KEY idx_training_notification_pilot_checks_status (check_status, evaluated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS training_notification_pilot_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    pilot_run_id BIGINT UNSIGNED NOT NULL,
    event_type VARCHAR(96) NOT NULL,
    severity ENUM('info','warning','critical','success') NOT NULL DEFAULT 'info',
    event_summary VARCHAR(255) NOT NULL,
    metadata_json JSON DEFAULT NULL,
    actor_user_id BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_training_notification_pilot_events_public (public_id),
    KEY idx_training_notification_pilot_events_run (pilot_run_id, created_at),
    KEY idx_training_notification_pilot_events_type (event_type, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
