<?php
require_once __DIR__ . '/../includes/labs-layout.php';
require_once __DIR__ . '/../includes/training-lab-app-service.php';
$campaigns = tl_app_campaign_options();
$rows = tl_stage40_participant_rows(100);
labs_page_start(['title' => 'Cohort Manager | Training Lab', 'section' => 'admin', 'active' => 'admin-cohort-manager']);
?>
<?php if (function_exists('tl_design_render_logged_in_template')) tl_design_render_logged_in_template('admin-cohort-manager'); ?>

<?php if (function_exists('tl_stage680_render_mission_followup_logic')) tl_stage680_render_mission_followup_logic(); ?>
<?php if (function_exists('tl_stage640_render_participant_data_quality')) tl_stage640_render_participant_data_quality((string)($_GET['campaign'] ?? ''), max(0, (int)($_GET['user_id'] ?? 0))); ?>


<section class="labs-page-title labs-stage40-title"><div><span class="labs-eyebrow">Cohort manager</span><h1>Manage the standalone Training Lab cohort.</h1><p class="labs-copy">Add participants, change Training Lab participant status, and jump into participant progress without touching the production user/auth system.</p></div><div class="labs-actions"><a class="labs-btn" href="<?php echo labs_url('/app/launchpad.php'); ?>">Participant Launchpad</a><a class="labs-btn labs-btn-primary" href="<?php echo labs_url('/admin/cohort-manager.php'); ?>">Cohort Manager</a></div></section>
<section class="labs-card"><div class="labs-card-headline"><div><span class="labs-eyebrow">Add participant</span><h2>Cohort invite / load</h2></div><span class="labs-pill">training_participants only</span></div><form action="<?php echo labs_url('/admin/action-result.php'); ?>" method="post" class="labs-stage30-form labs-stage40-form"><input type="hidden" name="confirm_training_action" value="1"><input type="hidden" name="training_action" value="cohort_invite"><label>Campaign<select name="campaign_id"><?php foreach ($campaigns as $campaign): ?><option value="<?php echo htmlspecialchars((string)$campaign['ref'], ENT_QUOTES, 'UTF-8'); ?>"><?php echo htmlspecialchars((string)$campaign['title'], ENT_QUOTES, 'UTF-8'); ?></option><?php endforeach; ?></select></label><label>User ID<input type="number" name="user_id" value="<?php echo max(1, count($rows) + 1); ?>" min="1"></label><label>Participant label<input type="text" name="participant_label" value="Training Participant <?php echo count($rows) + 1; ?>"></label><button class="labs-btn labs-btn-primary" type="submit">Add / Load Participant</button></form></section>
<section class="labs-card"><h2>Cohort table</h2><?php if (!$rows): ?><div class="labs-empty-state"><h3>No participants yet.</h3><p>Add a participant above or use the participant launchpad.</p></div><?php else: ?><div class="labs-stage40-table-wrap"><table class="labs-stage40-table"><thead><tr><th>Participant</th><th>Campaign</th><th>Status</th><th>Progress</th><th>Receipts</th><th>Actions</th></tr></thead><tbody><?php foreach ($rows as $row): ?><tr><td><strong><?php echo htmlspecialchars((string)$row['participant_label'], ENT_QUOTES, 'UTF-8'); ?></strong><small>User #<?php echo (int)$row['user_id']; ?></small></td><td><?php echo htmlspecialchars((string)$row['campaign_title'], ENT_QUOTES, 'UTF-8'); ?></td><td><span class="labs-pill"><?php echo htmlspecialchars((string)$row['status'], ENT_QUOTES, 'UTF-8'); ?></span></td><td><?php echo (int)$row['completed_action_count']; ?>/<?php echo (int)$row['target_action_count']; ?></td><td><?php echo (int)$row['receipt_count']; ?></td><td><form action="<?php echo labs_url('/admin/action-result.php'); ?>" method="post" class="labs-inline-form"><input type="hidden" name="confirm_training_action" value="1"><input type="hidden" name="training_action" value="update_participant_status"><input type="hidden" name="participant_id" value="<?php echo htmlspecialchars((string)$row['public_id'], ENT_QUOTES, 'UTF-8'); ?>"><select name="status"><option value="active">Active</option><option value="paused">Paused</option><option value="completed">Completed</option><option value="removed">Removed</option></select><button class="labs-btn" type="submit">Update</button></form><a class="labs-btn" href="<?php echo labs_url('/app/progress-map.php?campaign=' . rawurlencode((string)$row['campaign_slug']) . '&user_id=' . (int)$row['user_id']); ?>">Progress</a></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<section class="labs-safe-note">Cohort Manager writes only to Training Lab participant/streak/event rows. It does not create or alter production accounts, roles, or auth records.</section>
<?php labs_page_end(['section' => 'admin']); ?>
