<?php
require_once __DIR__ . '/../includes/labs-layout.php';
require_once __DIR__ . '/../includes/training-lab-onboarding.php';
$page=['title'=>'Merchant Setup | Training Lab','section'=>'admin','active'=>'admin-getting-started','required_role'=>'manager'];
$user=tl_product_require_page_access($page);$state=tl_onboarding_manager($user ?? []);labs_page_start($page);
?>
<section class="labs-product-hero"><article class="labs-product-hero-main"><span class="labs-product-kicker">Merchant setup</span><h1>Launch a complete proof-based training campaign.</h1><p>Move through campaign structure, task design, reward eligibility, publishing, and participant enrollment in the correct order.</p></article><aside class="labs-product-next"><div><span>Recommended next step</span><h2><?php echo labs_e((string)$state['next']['label']); ?></h2><p><?php echo labs_e((string)$state['next']['detail']); ?></p></div><a class="labs-btn labs-btn-primary" href="<?php echo htmlspecialchars(labs_url((string)$state['next']['href']),ENT_QUOTES,'UTF-8'); ?>">Continue Setup</a></aside></section>
<section class="labs-product-stats" aria-label="Merchant setup summary"><article class="labs-product-stat"><span>Campaigns</span><strong><?php echo (int)$state['counts']['campaigns']; ?></strong><small>created</small></article><article class="labs-product-stat"><span>Tasks</span><strong><?php echo (int)$state['counts']['tasks']; ?></strong><small>configured</small></article><article class="labs-product-stat"><span>Reward rules</span><strong><?php echo (int)$state['counts']['rules']; ?></strong><small>configured</small></article><article class="labs-product-stat"><span>Published</span><strong><?php echo (int)$state['counts']['published']; ?></strong><small>open or scheduled</small></article><article class="labs-product-stat"><span>Participants</span><strong><?php echo (int)$state['counts']['participants']; ?></strong><small>enrolled</small></article></section>
<section class="labs-product-card labs-onboarding-progress"><div><span class="labs-product-kicker">Launch readiness</span><h2><?php echo (int)$state['complete_count']; ?> of <?php echo (int)$state['total_count']; ?> steps complete</h2></div><div class="labs-product-progress" aria-label="<?php echo (int)$state['percent']; ?> percent complete"><span style="width:<?php echo (int)$state['percent']; ?>%"></span></div></section>
<section class="labs-onboarding-steps" aria-label="Merchant onboarding checklist"><?php foreach($state['steps'] as $index=>$step): ?><article class="labs-onboarding-step<?php echo $step['complete']?' is-complete':''; ?>"><span class="labs-onboarding-index" aria-hidden="true"><?php echo $step['complete']?'✓':$index+1; ?></span><div><span class="labs-product-status is-<?php echo $step['complete']?'success':'info'; ?>"><?php echo $step['complete']?'Complete':'Setup'; ?></span><h2><?php echo labs_e((string)$step['label']); ?></h2><p><?php echo labs_e((string)$step['detail']); ?></p></div><a class="labs-btn" href="<?php echo htmlspecialchars(labs_url((string)$step['href']),ENT_QUOTES,'UTF-8'); ?>"><?php echo $step['complete']?'Review':'Configure'; ?></a></article><?php endforeach; ?></section>
<section class="labs-safe-note">Merchant onboarding reads only campaigns owned by the trusted account. Administrators may review platform-wide setup; managers cannot view another merchant’s campaign readiness.</section>
<?php labs_page_end(['section'=>'admin']); ?>
