<?php
require_once __DIR__ . '/../includes/labs-layout.php';
require_once __DIR__ . '/../includes/training-lab-pilot-communications-actions.php';
$page = ['title'=>'Notification Incidents | Training Lab','section'=>'admin','active'=>'admin-notification-incidents','required_role'=>'admin'];
$user = tl_product_require_page_access($page);
tl_security_session_start();
$flash = $_SESSION['tl_pilot_communications_flash'] ?? null;
unset($_SESSION['tl_pilot_communications_flash']);
$data = tl_notifications_incidents($user, 200);
$provider = tl_notifications_provider_state();
labs_page_start($page);
?>
<section class="labs-product-hero"><article class="labs-product-hero-main"><span class="labs-product-kicker">Administrator incidents</span><h1>Resolve delivery failures without exposing recipient data.</h1><p>Review blocked and failed notifications, sanitized provider attempts, and hashed suppressions. All real sending remains behind the global worker and provider gates.</p></article><aside class="labs-product-next"><div><span>Provider state</span><h2><?php echo !empty($provider['can_process']) ? 'Ready' : 'Disabled'; ?></h2><p><?php echo labs_e((string)$provider['provider_name']); ?> adapter · no PHP mail fallback</p></div><a class="labs-btn" href="<?php echo labs_url('/admin/pilot-communications.php'); ?>">Pilot Dashboard</a></aside></section>
<?php if (is_array($flash)): ?><div class="labs-alert is-<?php echo labs_e((string)($flash['tone'] ?? 'info')); ?>" role="status"><?php echo labs_e((string)($flash['message'] ?? '')); ?></div><?php endif; ?>
<section class="labs-product-layout">
  <article class="labs-product-card"><span class="labs-product-kicker">Worker control</span><h2>Process an explicitly enabled batch</h2><p>This action fails closed unless global delivery, the worker, the provider adapter, and each campaign pilot are active.</p><form action="<?php echo labs_url('/admin/pilot-communications-action.php'); ?>" method="post" class="labs-actions"><?php echo tl_security_csrf_field(); ?><input type="hidden" name="communications_action" value="process_notification_batch"><label>Batch size<input type="number" name="limit" min="1" max="100" value="10"></label><button class="labs-btn labs-btn-primary" type="submit"<?php echo empty($provider['can_process']) ? ' disabled' : ''; ?>>Process Batch</button></form></article>
  <article class="labs-product-card"><span class="labs-product-kicker">Suppression control</span><h2>Protect a recipient from future sends</h2><p>The email is normalized and stored only as a SHA-256 hash. Operational pages display a short confirmation hash, never the address.</p><form action="<?php echo labs_url('/admin/pilot-communications-action.php'); ?>" method="post" class="labs-form-grid"><?php echo tl_security_csrf_field(); ?><input type="hidden" name="communications_action" value="add_notification_suppression"><label>Recipient email<input type="email" name="email" maxlength="254" required></label><label>Type<select name="suppression_type"><option value="manual">Manual</option><option value="hard_bounce">Hard bounce</option><option value="complaint">Complaint</option><option value="invalid_recipient">Invalid recipient</option><option value="policy">Policy</option></select></label><label>Reason<input type="text" name="reason" maxlength="255"></label><button class="labs-btn" type="submit">Add Suppression</button></form></article>
</section>
<section class="labs-product-card"><div class="labs-product-card-head"><div><span class="labs-product-kicker">Incident queue</span><h2>Blocked and failed notifications</h2><p>Error details are sanitized and limited to operational status.</p></div><span class="labs-product-status is-<?php echo count($data['incidents']) ? 'danger' : 'success'; ?>"><?php echo count($data['incidents']); ?> open</span></div><?php if (!$data['incidents']): ?><div class="labs-guided-empty"><h3>No open notification incidents.</h3><p>Failed or blocked items will appear here without recipient addresses or provider payloads.</p></div><?php else: ?><div class="labs-table-scroll"><table class="labs-table"><thead><tr><th>Campaign</th><th>Event</th><th>Status</th><th>Attempts</th><th>Error</th><th>Created</th></tr></thead><tbody><?php foreach ($data['incidents'] as $row): ?><tr><td><?php echo labs_e((string)$row['campaign_title']); ?></td><td><?php echo labs_e(str_replace('_',' ',(string)$row['event_type'])); ?></td><td><span class="labs-product-status is-danger"><?php echo labs_e((string)$row['outbox_status']); ?></span></td><td><?php echo (int)$row['attempt_count']; ?>/<?php echo (int)$row['max_attempts']; ?></td><td><strong><?php echo labs_e((string)$row['last_error_code']); ?></strong><small><?php echo labs_e((string)$row['last_error_detail']); ?></small></td><td><?php echo labs_e((string)$row['created_at']); ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<section class="labs-product-layout">
  <article class="labs-product-card"><div class="labs-product-card-head"><div><span class="labs-product-kicker">Suppression list</span><h2>Active and released recipients</h2></div></div><?php if (!$data['suppressions']): ?><div class="labs-guided-empty"><h3>No suppressions.</h3></div><?php else: ?><div class="labs-incident-list"><?php foreach ($data['suppressions'] as $row): ?><div class="labs-incident-row"><div><strong><?php echo labs_e((string)$row['suppression_type']); ?></strong><p><code><?php echo labs_e((string)$row['email_confirmation']); ?></code> · <?php echo labs_e((string)$row['reason']); ?></p></div><span class="labs-product-status is-<?php echo (string)$row['status']==='active'?'danger':'neutral'; ?>"><?php echo labs_e((string)$row['status']); ?></span><?php if ((string)$row['status']==='active'): ?><form action="<?php echo labs_url('/admin/pilot-communications-action.php'); ?>" method="post"><?php echo tl_security_csrf_field(); ?><input type="hidden" name="communications_action" value="release_notification_suppression"><input type="hidden" name="suppression_id" value="<?php echo labs_e((string)$row['public_id']); ?>"><button class="labs-btn" type="submit">Release</button></form><?php endif; ?></div><?php endforeach; ?></div><?php endif; ?></article>
  <article class="labs-product-card"><div class="labs-product-card-head"><div><span class="labs-product-kicker">Attempt ledger</span><h2>Sanitized provider history</h2></div></div><?php if (!$data['attempts']): ?><div class="labs-guided-empty"><h3>No delivery attempts.</h3></div><?php else: ?><div class="labs-incident-list"><?php foreach ($data['attempts'] as $row): ?><div class="labs-incident-row"><div><strong><?php echo labs_e((string)$row['attempt_status']); ?> · attempt <?php echo (int)$row['attempt_no']; ?></strong><p><?php echo labs_e((string)$row['provider_name']); ?> · <?php echo labs_e((string)($row['error_code'] ?: $row['response_code'])); ?> · <?php echo labs_e((string)$row['completed_at']); ?></p></div><code><?php echo labs_e(substr((string)$row['outbox_public_id'],0,12)); ?></code></div><?php endforeach; ?></div><?php endif; ?></article>
</section>
<section class="labs-safe-note">The attempt ledger never stores raw provider responses, full provider message IDs, authorization headers, cookies, passwords, or recipient addresses.</section>
<?php labs_page_end(['section'=>'admin']); ?>
