<?php
require_once __DIR__ . '/../includes/labs-layout.php';
require_once __DIR__ . '/../includes/training-lab-pilot-communications-reporting.php';
$page = ['title'=>'Pilot Reporting | Training Lab','section'=>'admin','active'=>'admin-pilot-reporting','required_role'=>'manager'];
$user = tl_product_require_page_access($page);
$report = tl_notifications_pilot_report($user);
labs_page_start($page);
?>
<section class="labs-product-hero"><article class="labs-product-hero-main"><span class="labs-product-kicker">Pilot reporting</span><h1>Engagement, completion, rewards, and communication health in one view.</h1><p>Metrics are derived from existing participant, receipt, proof, review, reward, and notification records and remain scoped to campaigns owned by the signed-in merchant.</p></article><aside class="labs-product-next"><div><span>Completion rate</span><h2><?php echo (int)($report['totals']['completion_rate'] ?? 0); ?>%</h2><p><?php echo (int)($report['totals']['completed_participants'] ?? 0); ?> of <?php echo (int)($report['totals']['participants'] ?? 0); ?> participants completed.</p></div><a class="labs-btn" href="<?php echo labs_url('/admin/pilot-communications.php'); ?>">Communications</a></aside></section>
<section class="labs-product-stats" aria-label="Pilot performance summary">
<?php foreach (['engagement_rate'=>'Engagement','completion_rate'=>'Completion','delivery_rate'=>'Delivery','proofs'=>'Proofs','reviews'=>'Reviews','rewards'=>'Rewards','incidents'=>'Incidents'] as $key=>$label): ?><article class="labs-product-stat<?php echo $key==='incidents' && (int)($report['totals'][$key] ?? 0)>0?' is-action':''; ?>"><span><?php echo labs_e($label); ?></span><strong><?php echo (int)($report['totals'][$key] ?? 0); ?><?php echo str_ends_with($key,'_rate')?'%':''; ?></strong><small>owner-scoped total</small></article><?php endforeach; ?>
</section>
<section class="labs-product-card"><div class="labs-product-card-head"><div><span class="labs-product-kicker">Campaign performance</span><h2>Controlled pilot outcomes</h2><p>Engagement means at least one verified task-completion receipt. Delivery rate compares delivered notifications with all synchronized notification events.</p></div></div><?php if (!$report['campaigns']): ?><div class="labs-guided-empty"><h3>No pilot campaign data.</h3><p>Create or import a campaign, add participants, and synchronize communications to populate this report.</p></div><?php else: ?><div class="labs-report-grid"><?php foreach ($report['campaigns'] as $campaign): ?><article class="labs-report-card"><div class="labs-product-card-head"><div><span class="labs-product-kicker"><?php echo labs_e((string)$campaign['status']); ?></span><h3><?php echo labs_e((string)$campaign['title']); ?></h3></div><span class="labs-product-status is-<?php echo (int)$campaign['incidents']>0?'danger':'success'; ?>"><?php echo (int)$campaign['incidents']; ?> incidents</span></div><dl><div><dt>Participants</dt><dd><?php echo (int)$campaign['participants']; ?></dd></div><div><dt>Engaged</dt><dd><?php echo (int)$campaign['engagement_rate']; ?>%</dd></div><div><dt>Completed</dt><dd><?php echo (int)$campaign['completion_rate']; ?>%</dd></div><div><dt>Proof / review</dt><dd><?php echo (int)$campaign['proofs']; ?> / <?php echo (int)$campaign['reviews']; ?></dd></div><div><dt>Rewards</dt><dd><?php echo (int)$campaign['rewards']; ?></dd></div><div><dt>Email delivery</dt><dd><?php echo (int)$campaign['delivery_rate']; ?>%</dd></div></dl></article><?php endforeach; ?></div><?php endif; ?></section>
<section class="labs-safe-note">Pilot reporting does not infer opens or clicks, track users across sites, expose recipient addresses, or create a second analytics identity. It reports only first-party Training Lab lifecycle records.</section>
<?php labs_page_end(['section'=>'admin']); ?>
