<?php
require_once __DIR__ . '/../includes/labs-layout.php';
require_once __DIR__ . '/../includes/training-lab-product-acceptance.php';
$page=['title'=>'Product Acceptance | Training Lab','section'=>'admin','active'=>'admin-product-acceptance','required_role'=>'admin'];
tl_product_require_page_access($page);$report=tl_product_acceptance_report();labs_page_start($page);
?>
<section class="labs-product-hero"><article class="labs-product-hero-main"><span class="labs-product-kicker">End-to-end acceptance</span><h1><?php echo $report['ready']?'Product acceptance is ready.':'Product acceptance is blocked.'; ?></h1><p>Review routes, services, database tables, acceptance assets, and protected authority boundaries before deployment.</p></article><aside class="labs-product-next"><div><span>Acceptance score</span><h2><?php echo (int)$report['score']; ?>%</h2><p><?php echo count($report['failed']); ?> blocking check<?php echo count($report['failed'])===1?'':'s'; ?>.</p></div><a class="labs-btn" href="<?php echo htmlspecialchars(labs_url('/admin/live-acceptance.php'),ENT_QUOTES,'UTF-8'); ?>">Production Readiness</a></aside></section>
<section class="labs-product-stats" aria-label="Acceptance category summary"><?php foreach($report['categories'] as $name=>$category): ?><article class="labs-product-stat<?php echo (int)$category['percent']<100?' is-action':''; ?>"><span><?php echo labs_e(ucfirst((string)$name)); ?></span><strong><?php echo (int)$category['percent']; ?>%</strong><small><?php echo (int)$category['passed']; ?>/<?php echo (int)$category['total']; ?> checks</small></article><?php endforeach; ?></section>
<section class="labs-product-card"><div class="labs-product-card-head"><div><span class="labs-product-kicker">Acceptance checklist</span><h2>Deployment blockers and verified requirements</h2><p>This page performs reads only. It cannot import SQL, change configuration, issue rewards, run workers, or call Microgifter.</p></div></div><div class="labs-acceptance-list"><?php foreach($report['checks'] as $check): ?><article class="labs-acceptance-row"><span class="labs-product-status is-<?php echo $check['passed']?'success':'danger'; ?>"><?php echo $check['passed']?'Pass':'Blocked'; ?></span><div><strong><?php echo labs_e((string)$check['label']); ?></strong><p><?php echo labs_e((string)$check['detail']); ?></p></div></article><?php endforeach; ?></div></section>
<section class="labs-safe-note">A 100% report confirms repository and schema readiness only. Production reward delivery remains disabled or limited unless every existing Stage 890–899 gate is explicitly satisfied.</section>
<?php labs_page_end(['section'=>'admin']); ?>
