<?php
require_once __DIR__ . '/../includes/labs-layout.php';
require_once __DIR__ . '/../includes/training-lab-reward-management.php';
$page=['title'=>'Reward Fulfillment | Training Lab','section'=>'admin','active'=>'admin-reward-bridge','required_role'=>'manager'];
$user=tl_product_require_page_access($page);
$state=tl_reward_management_fulfillment($user ?? [],150);
$c=$state['counts'];
labs_page_start($page);
?>
<section class="labs-product-hero"><article class="labs-product-hero-main"><span class="labs-product-kicker">Reward fulfillment</span><h1>Track reward delivery without operating the pipeline.</h1><p>See what is ready, processing, delivered, blocked, or failed. Existing Microgifter issuing and reconciliation controls remain protected.</p></article><aside class="labs-product-next"><div><span>Current health</span><h2><?php echo (int)$c['failed']>0?'Needs attention':((int)$c['processing']>0?'Delivery in progress':'Fulfillment is stable'); ?></h2><p><?php echo (int)$c['total']; ?> reward event<?php echo (int)$c['total']===1?'':'s'; ?> in scope.</p></div><?php if(!empty($state['advanced_available'])): ?><a class="labs-btn" href="<?php echo htmlspecialchars(labs_url('/admin/reward-operations.php'),ENT_QUOTES,'UTF-8'); ?>">Advanced Operations</a><?php endif; ?></aside></section>
<section class="labs-product-stats" aria-label="Reward fulfillment summary"><article class="labs-product-stat"><span>Ready</span><strong><?php echo (int)$c['ready']; ?></strong><small>eligible or queued</small></article><article class="labs-product-stat"><span>Processing</span><strong><?php echo (int)$c['processing']; ?></strong><small>delivery underway</small></article><article class="labs-product-stat"><span>Delivered</span><strong><?php echo (int)$c['delivered']; ?></strong><small>confirmed</small></article><article class="labs-product-stat"><span>Blocked</span><strong><?php echo (int)$c['blocked']; ?></strong><small>guarded</small></article><article class="labs-product-stat"><span>Failed</span><strong><?php echo (int)$c['failed']; ?></strong><small>operator review</small></article></section>
<section class="labs-product-card"><div class="labs-product-card-head"><div><span class="labs-product-kicker">Delivery activity</span><h2>Reward event health</h2><p>Confirmation references are one-way hashes. Adapter payloads, external IDs, idempotency keys, and account identifiers remain private.</p></div><a class="labs-btn labs-btn-primary" href="<?php echo htmlspecialchars(labs_url('/admin/reward-rules.php'),ENT_QUOTES,'UTF-8'); ?>">Reward Rules</a></div><?php if($state['rows']): ?><div class="labs-fulfillment-list"><?php foreach($state['rows'] as $row): ?><article class="labs-fulfillment-row"><div><span class="labs-product-status is-<?php echo (string)$row['health_bucket']==='delivered'?'success':((string)$row['health_bucket']==='failed'?'danger':((string)$row['health_bucket']==='blocked'?'warning':'info')); ?>"><?php echo labs_e(ucfirst((string)$row['health_bucket'])); ?></span><h3><?php echo labs_e((string)($row['reward_label'] ?: 'Training reward')); ?></h3><p><?php echo labs_e((string)$row['campaign_title']); ?> · <?php echo labs_e((string)($row['participant_label'] ?: 'Participant')); ?> · <?php echo labs_e((string)$row['display_value']); ?></p><?php if($row['last_error']): ?><small><?php echo labs_e((string)$row['last_error']); ?></small><?php endif; ?></div><dl><div><dt>Reward state</dt><dd><?php echo labs_e(ucwords(str_replace('_',' ',(string)$row['status']))); ?></dd></div><div><dt>Delivery state</dt><dd><?php echo labs_e(ucwords(str_replace('_',' ',(string)$row['handoff_status']))); ?></dd></div><div><dt>Attempts</dt><dd><?php echo (int)$row['attempt_count']; ?></dd></div><div><dt>Confirmation</dt><dd><code><?php echo labs_e((string)$row['confirmation']); ?></code></dd></div></dl></article><?php endforeach; ?></div><?php else: ?><div class="labs-product-empty"><h3>No reward fulfillment activity yet.</h3><p>Reward events appear after participants reach an active eligibility rule.</p></div><?php endif; ?></section>
<section class="labs-safe-note">This merchant page is read-only. Retrying, issuing, reconciliation, pilot, canary, and scheduler controls remain in the administrator-only Advanced Reward Operations console.</section>
<?php labs_page_end(['section'=>'admin']); ?>
