<?php
require_once __DIR__ . '/../includes/labs-layout.php';
require_once __DIR__ . '/../includes/training-lab-app-service.php';
$state = tl_stage45_scenario_state();
labs_page_start(['title' => 'Scenario Runner | Training Lab', 'section' => 'admin', 'active' => 'admin-scenario-runner']);
?>
<?php if (function_exists('tl_design_render_logged_in_template')) tl_design_render_logged_in_template('admin-scenario-runner'); ?>

<section class="labs-page-title labs-stage45-title"><div><span class="labs-eyebrow">Scenario runner</span><h1>Seed complete Training Lab practice scenarios.</h1><p class="labs-copy">Create a campaign, participants, and optional text proof samples in one controlled standalone action. This lets you demo the app flow quickly after upload/extract.</p></div><div class="labs-actions"><a class="labs-btn" href="<?php echo labs_url('/app/challenge-library.php'); ?>">Challenge Library</a><a class="labs-btn labs-btn-primary" href="<?php echo labs_url('/app/flow-board.php'); ?>">Flow Board</a></div></section>
<section class="labs-flow-grid"><article class="labs-card"><h2>Seed scenario</h2><form action="<?php echo labs_url('/admin/action-result.php'); ?>" method="post" class="labs-stage30-form labs-stage45-form"><input type="hidden" name="confirm_training_action" value="1"><input type="hidden" name="training_action" value="seed_training_scenario"><label>Scenario template<select name="template_id"><?php foreach ($state['templates'] as $id => $template): ?><option value="<?php echo htmlspecialchars($id, ENT_QUOTES, 'UTF-8'); ?>"><?php echo htmlspecialchars((string)$template['label'], ENT_QUOTES, 'UTF-8'); ?></option><?php endforeach; ?></select></label><label>Scenario title<input type="text" name="title" value="Review Practice Scenario"></label><label>Participant count<input type="number" name="participant_count" value="3" min="1" max="8"></label><label>Starting user ID<input type="number" name="start_user_id" value="20" min="1"></label><label class="labs-checkline"><input type="checkbox" name="include_sample_proofs" value="1" checked> Include sample text proofs</label><button class="labs-btn labs-btn-primary" type="submit">Seed Scenario</button></form></article><aside class="labs-card"><h2>Scenario output</h2><p class="labs-muted">After seeding, open the Flow Board, Review Workbench, Intervention Center, or Participant Progress Map to operate the scenario.</p><div class="labs-stage13-link-grid"><a href="<?php echo labs_url('/app/flow-board.php'); ?>"><span>Flow Board</span><strong>Open</strong></a><a href="<?php echo labs_url('/admin/review-workbench.php'); ?>"><span>Review</span><strong>Queue</strong></a><a href="<?php echo labs_url('/admin/review-workbench.php'); ?>"><span>Intervention</span><strong>Coach</strong></a><a href="<?php echo labs_url('/admin/cohort-manager.php'); ?>"><span>Certificate</span><strong>Complete</strong></a></div></aside></section>
<section class="labs-card"><h2>Available templates</h2><div class="labs-stage45-template-grid"><?php foreach ($state['templates'] as $id => $template): ?><div class="labs-stage45-template-card"><span><?php echo htmlspecialchars($id, ENT_QUOTES, 'UTF-8'); ?></span><strong><?php echo htmlspecialchars((string)$template['label'], ENT_QUOTES, 'UTF-8'); ?></strong><p><?php echo htmlspecialchars((string)$template['summary'], ENT_QUOTES, 'UTF-8'); ?></p></div><?php endforeach; ?></div></section>
<section class="labs-safe-note">Scenario Runner seeds only Training Lab campaign, task, participant, proof, and event rows. It does not reset or delete data and does not touch production systems.</section>
<?php labs_page_end(['section' => 'admin']); ?>
