<?php
$root=dirname(__DIR__);$read=static fn(string $path):string=>(string)file_get_contents($root.'/'.$path);
$service=$read('includes/training-lab-production-integration-closeout.php');$page=$read('admin/integration-closeout.php');$action=$read('admin/integration-closeout-action.php');$api=$read('api/training/integration-closeout.php');$cli=$read('bin/integration-closeout.php');$migration=$read('database/production_integration_closeout_v1.sql');$config=$read('labs/config-example.php');$acceptance=$read('includes/training-lab-product-acceptance.php');$gate=$read('run-quality-gate.sh');$workflow=$read('.github/workflows/quality-gate.yml');$docs=$read('docs/PRODUCTION-INTEGRATION-CLOSEOUT-V1.md');
$categories=[
'Durable evidence'=>[str_contains($migration,'training_integration_closeout_runs'),str_contains($migration,'training_integration_closeout_checks'),str_contains($migration,'training_integration_closeout_events'),str_contains($migration,'report_hash CHAR(64)')],
'Shared account'=>[str_contains($service,'account_link_active'),str_contains($service,'account_authenticated'),str_contains($service,'nonce_consumed')],
'Participant flow'=>[str_contains($service,'campaign_builder_ready'),str_contains($service,'proof_approved'),str_contains($service,'task_receipt'),str_contains($service,'sequence_receipt')],
'Email delivery'=>[str_contains($service,'pilot_graduated'),str_contains($service,'canary_delivered'),str_contains($service,'participant_delivered'),str_contains($service,'no_terminal_delivery')],
'Reward confirmation'=>[str_contains($service,'handoff_delivered'),str_contains($service,'external_reference'),str_contains($service,'signed_lookup_ready'),str_contains($service,'stage895_passed')],
'Approval integrity'=>[str_contains($service,'report_hash'),str_contains($service,'hash_equals'),str_contains($service,'integration_closeout_evidence_changed'),str_contains($service,'integration_closeout_approved_immutable')],
'Authority boundaries'=>[!preg_match('/\b(?:curl_|training_lab_send_notification_email|microgifter_training_reward_issue|tl_stage896_execute|tl_stage899_process)\b/i',$service.$action),!str_contains($service,'UPDATE training_reward_handoffs'),!str_contains($service,'UPDATE training_notification_outbox'),str_contains($service,'no_gate_activation')],
'Operations'=>[str_contains($page,'Production Integration Closeout'),str_contains($api,"tl_security_require_method('GET')"),str_contains($cli,"PHP_SAPI !== 'cli'"),str_contains($action,'tl_security_guard_write')],
'Disabled-first config'=>[str_contains($config,"production_integration_closeout_enabled' => false"),str_contains($config,"production_integration_closeout_approval_enabled' => false"),str_contains($service,'integration_closeout_disabled'),str_contains($service,'integration_closeout_approval_disabled')],
'Acceptance deployment'=>[str_contains($acceptance,"integration_closeout'=>'admin/integration-closeout.php'"),str_contains($gate,'production-integration-closeout-quality-audit.php'),str_contains($workflow,'Production integration closeout scored audit'),str_contains($docs,'Rollback'),str_contains($docs,'Emergency stop')],
];
$total=0;foreach($categories as $name=>$checks){$passed=count(array_filter($checks));$score=(int)round($passed/max(1,count($checks))*10);$total+=$score;echo sprintf("%-34s %d/10 (%d/%d)\n",$name,$score,$passed,count($checks));}echo 'Section 20 total: '.$total."/100\n";if($total!==100)exit(1);echo "Section 20 source score: 10/10 in every category.\n";
