<?php
declare(strict_types=1);
$root=dirname(__DIR__);$files=[];$load=static function(string $path)use($root,&$files):string{return $files[$path]??=is_file($root.'/'.$path)?(file_get_contents($root.'/'.$path)?:''):'';};$has=static fn(string $p,string $n):bool=>str_contains($load($p),$n);$lacks=static fn(string $p,string $n):bool=>!str_contains($load($p),$n);$exists=static fn(string $p):bool=>is_file($root.'/'.$p);
$sections=[
'Owner isolation'=>[$has('includes/training-lab-reward-management.php','c.owner_user_id=?'),$has('includes/training-lab-reward-management.php',"'platform'=>\$role === 'admin'"),$has('includes/training-lab-reward-management.php','tl_campaign_user_id($user)'),$lacks('includes/training-lab-reward-management.php','$_GET'),$lacks('includes/training-lab-reward-management.php','$_POST')],
'Rule editing'=>[$exists('admin/reward-rules.php'),$exists('admin/reward-rule-edit.php'),$has('admin/reward-rule-edit.php','Participant preview'),$has('admin/reward-rule-edit.php','tl_security_csrf_field()'),$has('includes/training-lab-reward-management.php','reward_rule_updated')],
'Lifecycle safety'=>[$has('includes/training-lab-reward-management.php',"'draft'=>['activate'=>'active','archive'=>'archived']"),$has('includes/training-lab-reward-management.php',"'active'=>['pause'=>'paused','archive'=>'archived']"),$has('includes/training-lab-reward-management.php',"'paused'=>['resume'=>'active','archive'=>'archived']"),$has('includes/training-lab-reward-management.php','reward_rule_archived'),$has('includes/training-lab-reward-management.php','campaign_archived')],
'Transaction safety'=>[$has('includes/training-lab-reward-management.php','beginTransaction()'),$has('includes/training-lab-reward-management.php','LIMIT 1 FOR UPDATE'),$has('includes/training-lab-reward-management.php','$pdo->commit();'),$has('includes/training-lab-reward-management.php','if ($pdo->inTransaction()) $pdo->rollBack();'),$has('includes/training-lab-reward-management.php','tl_log_event')],
'Analytics accuracy'=>[$has('includes/training-lab-reward-management-queries.php',"re.status IN ('issued','linked')"),$has('includes/training-lab-reward-management-queries.php','TIMESTAMPDIFF(MINUTE'),$has('admin/analytics.php','Campaign funnel'),$has('admin/analytics.php','completion_rate'),$has('admin/analytics.php','delivery_rate')],
'Fulfillment privacy'=>[$has('includes/training-lab-reward-management-queries.php','h.handoff_status'),$has('includes/training-lab-reward-management-queries.php','h.failure_message'),$has('includes/training-lab-reward-management-queries.php',"substr(hash('sha256'"),$lacks('includes/training-lab-reward-management-queries.php','payload_json'),$lacks('includes/training-lab-reward-management-queries.php','idempotency_key')],
'Operations separation'=>[$has('admin/reward-bridge.php','Track reward delivery without operating the pipeline.'),$lacks('admin/reward-bridge.php','tl_stage890_render_admin_panel'),$has('admin/reward-operations.php',"'required_role'=>'admin'"),$has('admin/reward-operations.php','tl_stage890_render_admin_panel'),$has('admin/reward-operations.php','tl_stage899_render_reward_bridge_panel')],
'Responsive accessibility'=>[$exists('assets/css/reward-management.css'),$has('assets/css/reward-management.css','@media(max-width:900px)'),$has('assets/css/reward-management.css','@media(max-width:620px)'),$has('admin/analytics.php','role="region"'),$has('admin/reward-bridge.php','aria-label="Reward fulfillment summary"')],
'Navigation and routes'=>[$has('includes/training-lab-product-shell.php','admin-reward-rules'),$has('includes/training-lab-product-shell.php','admin-analytics'),$has('includes/training-lab-product-shell.php','admin-reward-operations'),$has('admin/reward-rule-save.php',"tl_security_guard_write('evaluate_rewards'"),$has('admin/reward-rule-status.php',"tl_security_guard_write('evaluate_rewards'")],
'Acceptance and authority'=>[$exists('tests/reward-rules-analytics-operational-health-contract-test.php'),$exists('docs/REWARD-RULES-ANALYTICS-OPERATIONAL-HEALTH-V1.md'),$has('docs/REWARD-RULES-ANALYTICS-OPERATIONAL-HEALTH-V1.md','No SQL is required.'),$has('includes/training-lab-reward-management.php',"'wallet_write'=>false"),$has('docs/REWARD-RULES-ANALYTICS-OPERATIONAL-HEALTH-V1.md','It does not create a second account, merchant, role, reward issuer, wallet, payment, claim, redemption, gift, or delivery authority.')],
];
$failed=false;echo "Reward Rules, Analytics + Operational Health quality audit\n";foreach($sections as $name=>$checks){$passed=count(array_filter($checks));$total=count($checks);$score=round($passed/$total*10,1);echo sprintf("%-30s %s/10 (%d/%d checks)\n",$name,number_format($score,$score===10.0?0:1),$passed,$total);if($passed!==$total)$failed=true;}if($failed){fwrite(STDERR,"Section 10 has not reached 10/10 in every category.\n");exit(1);}echo "Every Section 10 category scored 10/10.\n";
